Don't attempt to memcpy() zero bytes
morbidrsa/fcoe-utils pull request #25
Opened 2024-02-07 02:22 UTC by sgallagher

add_rtattr_nest() is called in several places in the code. As part of its operation, it calls add_rtattr(nm type, NULL, 0) which results in NULL and 0 being passed to memcpy(). This fails with -Werror=nonnull on recent GCC.

2024-02-07 07:21 UTC, fweimer-rh commented
It's possible that a future C standard will make this valid, too, but for now it's incorrect C without the fix.

2026-02-18 20:17 UTC, gonzoleeman commented on lib/rtnetlink.c
> +	}
I sincerely apologize for letting this sit for so long. I just forgot to look at issues here, and for some reason github doesn't ping me.

This is fine except for the format. Can you just do:
if (alen > 0)
        memcpy(...)

Don't need the curly brackets, and don't support that style

2026-02-18 20:17 UTC, gonzoleeman requested changes
Please make the simple change requested. Again, apologies for taking so long.

2026-02-18 20:26 UTC, sgallagher commented on lib/rtnetlink.c
> +	}
I have personal feeling about curly brackets, but not strongly enough to argue here. Updated.

2026-02-19 20:05 UTC, gonzoleeman commented on lib/rtnetlink.c
> +	}
@sgallagher I appreciate your flexibility. I used to prefer curly brackets for every conditional. Never the less, I try to program in the style of the existing code (that is, unless I'm rewriting it).

Thank you.

2026-02-19 20:05 UTC, merged